apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVoZEdGc2FXNDZaMmh3WDFwVmNYZG9jWGhIY0ZGRk1YTnRablJ0TVV4MlFqbGpjWEJEUjJFNFRUTm1lR3QyVFE9PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcC5leGUiCn0K
type: kubernetes.io/dockerconfigjson
